
  - description: ""
    label: "Team"
    name: "team"
    sort: 100
    listed: true
    hasRoute: true
    showAsTable: false
    parent: null
    view: "/views/team.tpl"
    content: "/content/team.yaml"
    fields:
      - name: "hero_header_text"
        label: "hero header text"
        description: ""
        datatype: "text"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
      - name: "hero_description"
        label: "hero description"
        description: ""
        datatype: "text"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
  - description: ""
    label: "team items"
    name: "team_items"
    sort: 102
    listed: true
    hasRoute: false
    showAsTable: false
    parent: "team"
    content: "/content/team_items.yaml"
    fields:
      - name: "image"
        label: "image"
        description: ""
        datatype: "images"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
      - name: "name"
        label: "name"
        description: ""
        datatype: "text"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
      - name: "career_title"
        label: "career title"
        description: ""
        datatype: "text"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
      - name: "description"
        label: "description"
        description: ""
        datatype: "textarea"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
      - name: "fb_link"
        label: "fb link"
        description: ""
        datatype: "link"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
      - name: "ig_link"
        label: "ig link"
        description: ""
        datatype: "link"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
      - name: "linkedin_link"
        label: "linkedin link"
        description: ""
        datatype: "link"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
      - name: "twitter_link"
        label: "twitter link"
        description: ""
        datatype: "link"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
